- id: '1734320711731'
  alias: Sunset Duck Path
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: 0
  conditions: []
  actions:
  - type: turn_on
    device_id: 9f3dd1ae636000f853bd58509c4f3cbe
    entity_id: 32291415ff6d901f6839ddeab44f0387
    domain: light
    brightness_pct: 100
  mode: single
- id: '1734320852612'
  alias: Sunset Duck Path
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: 0
  conditions: []
  actions:
  - type: turn_on
    device_id: 9f3dd1ae636000f853bd58509c4f3cbe
    entity_id: 32291415ff6d901f6839ddeab44f0387
    domain: light
    brightness_pct: 100
  mode: single
- id: '1747367874759'
  alias: Bathroom Humidity Exhaust Fan
  description: ''
  use_blueprint:
    path: Blackshome/bathroom-humidity-exhaust-fan.yaml
    input:
      fan_switch:
        device_id: 0b96ae17ef2ab2d15baa07bc0b2231fe
      trigger: sensor.master_bathroom_humidity_change
      bathroom_humidity_sensor: sensor.tp357s_d8de_humidity
