homeassistant:
  packages: !include_dir_named packages

# Loads default set of integrations. Do not remove.
default_config:
# Example configuration.yaml entry with exclude
recorder:
  purge_keep_days: 5
  #db_url: sqlite:////home/user/.homeassistant/test
  # include:
  #   entities:
  #     - input_boolean.gh_station0
  #     - input_boolean.gh_station1
  #     - input_boolean.gh_station2
  #     - input_boolean.gh_station3
  #     - input_boolean.gh_station4
  #     - input_boolean.gh_station5
  #     - input_boolean.gh_station6
  #     - input_boolean.gh_station7
  #     - input_boolean.gh_station8
  #     - input_boolean.gh_station9
  #     - input_boolean.gh_station10
  #     - input_boolean.gh_station11

logger:
  default: critical
  logs:
    # logs levels
    #   critical fatal error warning warn info debug notset
    #
    # log level for HA core
    homeassistant.core: fatal
    # log level for MQTT integration
    #homeassistant.components.mqtt: info
    # log level for all python scripts
    homeassistant.components.python_script: error
    # individual log level for this python script
    homeassistant.components.python_script.esp_cmd.py: info
    homeassistant.components.python_script.on_boot.py: info
    homeassistant.components.python_script.set_gh_stations.py: info
    homeassistant.components.python_script.test.py: info

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

python_script:

sensor:
  - platform: temper
    name: GH_temp

remember_the_milk:
  - name: !secret rmilk_name
    api_key: !secret rmilk_api_key
    shared_secret: !secret rmilk_shared_secret

# Text to speech
tts:
  - platform: google_translate

automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml
