alias: On Boot Automations
initial_state: "on"
trigger:
  - platform: homeassistant
    enabled: true
    event: start
    action:
      - service: python_script.on_boot
        data:
          message: ""
      - service: shell_command.renew_ip
        response_variable: todo_response
