logger.info("py:timed_task:info:start")
#logger.debug("py:timed_task:debug: script running")
#logger.error("py:timed_task:error: script running")
t = time.localtime()
current_time = time.strftime("%H:%M:%S", t)
logger.info(current_time) 
logger.info("py:timed_task:info:end")