- alias: "Sunrise Barn lights on"
  trigger:
    - platform: time
      at:  "05:30:00"  # on at 530a regardless of sunrise
  condition: []
  action:
    - service: homeassistant.turn_on
      entity_id: switch.eggbarn_light

# simplifying trigger - https://community.home-assistant.io/t/best-practices-for-on-off-within-the-same-automation/330121
# min light with poultry - https://community.home-assistant.io/t/chicken-eggs/139971/27

- alias: "Morning Barn lights off"
  trigger:
    - platform: time
      at: "10:00:00"  # turn them off at 10a regardless of sunrise
  condition: []
  action:
    - service: homeassistant.turn_off
      entity_id: switch.eggbarn_light

- alias: "Sunset Barn lights on"
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00" # 1 hour before sunset
  condition: []
  action:
    - service: homeassistant.turn_on
      entity_id: switch.eggbarn_light

- alias: "Night Barn lights off"
  trigger:
    - platform: sun
      event: sunset
      offset: '{{ states.sensor.daylightboostduck.state) }}' # either at or after sunset
  condition: []
  action:
    - service: homeassistant.turn_off
      entity_id: switch.eggbarn_light
