- alias: "Sunrise Barn lights on"
  trigger:
    - platform: sun
      event: sunrise
      offset: 0
  condition: []
  action:
    - service: homeassistant.turn_on
      entity_id: switch.eggbarn_light

- alias: "Morning Barn lights off"
  trigger:
    - platform: time
      at: "08:00:00" # 8am
  condition: []
  action:
    - service: homeassistant.turn_off
      entity_id: switch.eggbarn_light

- alias: "Sunset Barn lights on"
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00" # 1 hour before sunset
  condition: []
  action:
    - service: homeassistant.turn_on
      entity_id: switch.eggbarn_light

- alias: "Night Barn lights off"
  trigger:
    - platform: sun
      event: sunset
      offset: "01:00:00" # 1 hours after sunset
  condition: []
  action:
    - service: homeassistant.turn_off
      entity_id: switch.eggbarn_light
