- alias: "Sunrise Barn lights on"
  trigger:
    - platform: sun
      event: sunrise
      offset:  "-00:10:00" # 10 minutes before sunset
  condition: []
  action:
    - service: homeassistant.turn_on
      entity_id: switch.eggbarn_light

- alias: "Morning Barn lights off"
  trigger:
    - platform: sunrise
      at: "03:00:00" # 3 hours after sunrise
  condition: []
  action:
    - service: homeassistant.turn_off
      entity_id: switch.eggbarn_light

- alias: "Sunset Barn lights on"
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00" # 1 hour before sunset
  condition: []
  action:
    - service: homeassistant.turn_on
      entity_id: switch.eggbarn_light

- alias: "Night Barn lights off"
  trigger:
    - platform: sun
      event: sunset
      offset: "01:00:00" # 1 hours after sunset
  condition: []
  action:
    - service: homeassistant.turn_off
      entity_id: switch.eggbarn_light
