- alias: "Sunrise Barn lights on"
  trigger:
    - platform: time
      at:  "05:30:00"  # on at 530a regardless of sunrise
  condition: []
  action:
    - service: homeassistant.turn_on
      entity_id: switch.eggbarn_light

# simplifying trigger - https://community.home-assistant.io/t/best-practices-for-on-off-within-the-same-automation/330121
# min light with poultry - https://community.home-assistant.io/t/chicken-eggs/139971/27

- alias: "Morning Barn lights off"
  trigger:
    - platform: time
      at: "10:00:00"  # turn them off at 10a regardless of sunrise
  condition: []
  action:
    - service: homeassistant.turn_off
      entity_id: switch.eggbarn_light

- alias: "Sunset Barn lights on"
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00" # 1 hour before sunset
  condition: []
  action:
    - service: homeassistant.turn_on
      entity_id: switch.eggbarn_light

- alias: "Night Barn lights off"
  trigger:
    - platform: sun
      event: sunset
  condition: []
  action:
    - variables:
        lightboost: >
          {% set d = states('sensor.duckdaylightboost') %}
          {% set h,m,s = d.split(':') | map('int') | list %}
          {% set tst = "00:00:00" %} 
          {% set tstr = '{:02d}:{:02d}:{:02d}'.format(h, m, s) %}
          {{ tstr }}
    - delay: "{{ lightboost }}"
    - service: homeassistant.turn_off
      entity_id: switch.eggbarn_light


