- alias: "Sunset Greenhouse lights on"
  trigger:
    - platform: sun
      event: sunset
      offset: 0
  condition: []
  action:
    - service: homeassistant.turn_on
      entity_id: group.gh_plant_light_group
#    service: python_script.set_unit_state
#    data:
#      name: group.gh_plant_light_group
#      state: "on"

- alias: "Sunrise Greenhouse lights off"
  trigger:
    - platform: sun
      event: sunrise
      offset: 0
  condition: []
  action:
    - service: homeassistant.turn_off
      entity_id: group.gh_plant_light_group
#    service: python_script.set_unit_state
#    data:
#      name: group.gh_plant_light_group
#      state: "off"


