# alias: "Hydroponic Cycle"
# trigger:
#   - platform: state
#     entity_id: switch.sengled_e1c_nb7_e08a6b03_on_off
#     for: '1:00:00'
#     to: 'off'
# condition: []
# action:
#   - service: switch.turn_on
#     target:
#       entity_id: switch.sengled_e1c_nb7_e08a6b03_on_off
#   - delay: '00:30:00'
#   - service: switch.turn_off
#     target:
#       entity_id: switch.sengled_e1c_nb7_e08a6b03_on_off
# mode: single


- alias: Hydroponic Cycle
  description: 'ON for 10 minutes, OFF for 30 minutes'
  id: the_toggler
  trigger:
  - platform: time_pattern
    minutes: '/10'
  action:
  - variables:
      sw: 'switch.osw1a'
      sw_is_on: "{{ is_state(sw, 'on') }}"
      time_on: '{{ now() - states[sw].last_changed >= timedelta(minutes=10) }}'
      time_off: '{{ now() - states[sw].last_changed >= timedelta(minutes=30) }}'
  - choose:
    - conditions: '{{ sw_is_on and time_on }}'
      sequence:
      - service: switch.turn_off
        target:
          entity_id: '{{ sw }}'
    - conditions: '{{ not sw_is_on and time_off }}'
      sequence:
      - service: switch.turn_on
        target:
          entity_id: '{{ sw }}'