- alias: "IP Address Change"
  initial_state: on
  trigger:
    - platform: state
      entity_id: sensor.myip
  action:
    - service: shell_command.renew_ip
      data:
        dynhost: !secret sdynhost
        dynuname: !secret sdynuname
        dynkey: !secret sdynkey
