- alias: "IP Address Change"
  initial_state: on
  trigger:
    - platform: state
      entity_id: sensor.myip
  action:
    - service: shell_command.renew_ip
      data:
        url_txt: "https://{{ dynip_hostname }}:{{ dynip_key }}@api.cp.easydns.com/dyn/generic.php?hostname={{ dynip_host }}&myip={{ states('sensor.myip' )}}"
      response_variable: todo_response
    #- service: notify.YOU
    #  data_template:
    #    message: "New external IP address is {{ states('sensor.myip') }}"

    #- if: "{{ todo_response['returncode'] == 0 }}"
    #  then:
    #    - service: notify.mobile_app_iphone
    #      data:
    #        title: "ToDo"
    #        message: "{{ todo_response['stdout'] }}"
    #  else:
    #    - service: notify.mobile_app_iphone
    #      data:
    #        title: "ToDo file error"
    #        message: "{{ todo_response['stderr'] }}"
