- alias: "Irrigation Test"
  trigger:
    - platform: state
      entity_id: input_button.test_irr
  action:
    - service: python_script.esp_cmd
      data:
        message: "z1_flower_path:on"
    - delay: 00:{{ states.input_number.time_z1_flower_path.state | int }}:00  # HH:MM:SS  #time_z1_flower_path
    - service: python_script.esp_cmd