# restarts HA every night at 11pm on Sunday
- alias: Restart HA
  trigger: 
    platform: time
    at: "23:00:00"  
  condition:
    condition: time
    weekday:
    - sun
  action:
    - service: homeassistant.restart