- alias: "Sunrise ring light pattern"
  trigger:
    - platform: sun
      event: sunrise
      offset: "-00:30:00" # before sunrise
  condition: []
  action:
    - service: homeassistant.turn_on
      entity_id: light.snack_light
    - delay: "00:{{ (range(30, 55)|random|int) }}:00" # random delay
    - service: homeassistant.turn_off
      entity_id: light.snack_light

- alias: "Sunset Ring light pattern"
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:05:00" # 5 minutes before sunset
  condition: []
  action:
    - service: homeassistant.turn_on
      entity_id: light.snack_light
    - delay: "00:{{ (range(10, 30)|random|int) }}:00" # random delay
    - service: homeassistant.turn_off
      entity_id: light.snack_light