- alias: "Test Script shot Btn"
  trigger:
    - platform: state
      entity_id: input_button.test_script_btn
  action:
    - service: python_script.{{ states('input_text.text_script_name') }}
      data:
        message: "{{ states('input_text.text_script_message') }}"
