- alias: "Test Script shot Btn"
  trigger:
    - platform: state
      entity_id: input_button.test_script_btn
  action:
    - service: python_script.test_helper  # service: python_script.{{ states('input_text.text_script_name') }} 
      data:
        parm1: "{{ states('input_text.text_script_parm1') }}"
        parm2: "{{ states('input_text.text_script_parm2') }}"
        parm3: "{{ states('input_text.text_script_parm3') }}"
        script: "{{ states('input_text.text_script_name') }}"
        
- alias: "Test Script ip change Btn"
  trigger:
    - platform: state
      entity_id: input_button.test_ip
  action:
    - service: shell_command.renew_ip
      data:
        dynhost: !secret sdynhost
        dynuname: !secret sdynuname
        dynkey: !secret sdynkey

