substitutions:
  name: patio-btproxy
  friendly_name: patio-btproxy
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main

ota:
  #password: "XXX"
  platform: esphome

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: "J2FPyNpJMRvy8RJTNdvseaELa6BGtpzobd4lKV6Zvzo="


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password