substitutions:
  device_name: "tst2c"
  device_friendlyname: "test_2channel"
  device_description: "test device 2 channel fet"
  device_board: d1_mini

#<<: !include common/board.yaml  
<<: !include common/board.yaml 
<<: !include common/fet2c.yaml