substitutions:
  device_name: "tst6c"
  device_friendlyname: "test_6channel"
  device_description: "test device 6 channel fet"
  device_board: d1_mini

#<<: !include common/board.yaml  
<<: !include common/board.yaml 
<<: !include common/fet6c.yaml