esphome:
  name: tst6c
  friendly_name: tst6c

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "J2FPyNpJMRvy8RJTNdvseaELa6BGtpzobd4lKV6Zvzo="

ota:
  #password: "755d7093731b31ad1d1c2987f8292e79"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tst6C Fallback Hotspot"
    password: "sunflower"

captive_portal:

switch:
  - platform: gpio
    pin:
      number: D3
      mode:
        output: true
        #pulldown: true
    name: "bit3" 
    id: bit3
  - platform: gpio
    pin:
      number: D1
      mode:
        output: true
        #pulldown: true
    name: "bit2" 
    id: bit2
  - platform: gpio
    pin:
      number: D2
      mode:
        output: true
        #pulldown: true
    name: "bit1" 
    id: bit1
    