bed2substitutions:
  device_name: "z1-bed1"
  device_friendlyname: "z1-bed1"
  device_description: "zone 1 bed 1"
  device_board: d1_mini

#<<: !include common/board.yaml  
<<: !include common/board.yaml 
<<: !include common/fet1c.yaml 