substitutions:
  device_name: "z1-grid56"
  device_friendlyname: "z1-grid56"
  device_description: "zone 1 grid 5 and 6"
  device_board: d1_mini

#<<: !include common/board.yaml  
<<: !include common/board.yaml 
<<: !include common/fet2c.yaml