substitutions:
  device_name: "z1-grid12"
  device_friendlyname: "z1-grid12"
  device_description: "zone 1 grid 1 and 2"
  device_board: d1_mini

#<<: !include common/board.yaml  
<<: !include common/board.yaml 
<<: !include common/fet2c.yaml