substitutions:
  device_name: "z2-bay-bush"
  device_friendlyname: "z2-bay-bush"
  device_description: "zone 2 bay bush"
  device_board: d1_mini

#<<: !include common/board.yaml  
<<: !include common/board.yaml 
<<: !include common/fet1c.yaml 