substitutions:
  device_name: "z2-tub56"
  device_friendlyname: "z2-tub56"
  device_description: "zone 2 tub 5 and 6"
  device_board: d1_mini

#<<: !include common/board.yaml  
<<: !include common/board.yaml 
<<: !include common/fet2c.yaml