substitutions:
  device_name: "z2-tub12"
  device_friendlyname: "z2-tub12"
  device_description: "zone 2 tub 1 and 2"
  device_board: d1_mini

#<<: !include common/board.yaml  
<<: !include common/board.yaml 
<<: !include common/fet2c.yaml