substitutions:
  device_name: "z2-tub7"
  device_friendlyname: "z2-tub7"
  device_description: "zone 2 tub 7"
  device_board: d1_mini

#<<: !include common/board.yaml  
<<: !include common/board.yaml 
<<: !include common/fet1c.yaml 